# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: mqtt-secrets
# data:
#   MQTT_PORT:
#   MQTT_USER7P7XWK:
#   MQTT_PASS7P7XWK:
#   MQTT_CLIENTID7P7XWK:
#   MQTT_HOST7P7XWK:
#   MQTT_CLIENTID5YRUSP:
#   MQTT_USER5YRUSP:
#   MQTT_PASS5YRUSP:
#   CLOUDANT_HOST:
#   OPENEEW_API_KEY:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openeew-devicemgmt
  labels:
    app: openeew-devicemgmt
spec:
  selector:
    matchLabels:
      app: openeew-devicemgmt
  template:
    metadata:
      labels:
        app: openeew-devicemgmt
    spec:
      containers:
      - name: devicemgmt
        image: us.icr.io/openeew-devicemgmt/openeew-devicemgmt:2.2
        ports:
        - containerPort: 1880
        envFrom:
        - secretRef:
            name: mqtt-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: openeew-devicemgmt
  labels:
    app: openeew-devicemgmt
spec:
  type: NodePort
  ports:
  - port: 1880
    targetPort: 1880
    protocol: TCP
    name: http
  selector:
    app: openeew-devicemgmt
